def return_type_cubo(left_oper,right_oper,operator):
    return cubo_semantico[left_oper][right_oper][operator]
cubo_semantico = {
   'int':{
        'int':{
            '+': 'int',
            '-': 'int',
            '/': 'int',
            '*': 'int',
            '<': 'bool',
            '>': 'bool',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool',
            '=': True
            
        },
        'float':{
            '+': 'float',
            '-': 'float',
            '/': 'float',
            '*': 'float',
            '<': 'bool',
            '>': 'bool',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool',
            '=': False

        },
        'bool':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False

        },
        'char':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False

        }
    },
    'float':{
        'int':{
            '+': 'float',
            '-': 'float',
            '/': 'float',
            '*': 'float',
            '<': 'bool',
            '>': 'bool',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool',
            '=': True
        },
        'float':{
            '+': 'float',
            '-': 'float',
            '/': 'float',
            '*': 'float',
            '<': 'bool',
            '>': 'bool',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool',
            '=': True
        },
        'bool':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        },
        'char':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        }
    },
    'bool':{
        'int':{
           '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        },
        'float':{
           '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        },
        'bool':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'bool',
            '|': 'bool',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': True
        },
        'char':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '<>': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        }
    },
    'char':{
        'int':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        },
        'float':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        },
        'bool':{
             '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '<>': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err',
            '=': False
        },
        'char':{
            '+': 'char',
            '-': 'char',
            '/': 'char',
            '*': 'char',
            '<': 'err',
            '>': 'err',
            '&&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool',
            '=': True
        }
    }
}